# Generated by Django 5.1.3 on 2024-12-02 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("phone_num", models.CharField(max_length=20, unique=True)),
                ("pwd", models.CharField(max_length=255)),
                ("dob", models.DateField()),
                ("address", models.CharField(max_length=255)),
                (
                    "my_pay_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
            ],
        ),
    ]
