# Generated by Django 5.1.3 on 2024-12-02 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yellow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="yellow.user",
                    ),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("acc_number", models.CharField(max_length=50, unique=True)),
                ("npwp", models.CharField(max_length=50, unique=True)),
                ("pic_url", models.URLField(blank=True, null=True)),
                ("rate", models.FloatField(default=0.0)),
                ("total_finish_order", models.IntegerField(default=0)),
            ],
        ),
    ]
